USE [master]
GO

/****** Object:  Database [MYB]    Script Date: 16/09/2020 19:28:54 ******/
CREATE DATABASE [MYB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MYB_Normal_Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MYB.mdf' , SIZE = 541056KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'MYB_Normal_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MYB_log.ldf' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MYB].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [MYB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MYB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MYB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MYB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MYB] SET ARITHABORT OFF 
GO

ALTER DATABASE [MYB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MYB] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [MYB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MYB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MYB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MYB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MYB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MYB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MYB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MYB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MYB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MYB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MYB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MYB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MYB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MYB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MYB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MYB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MYB] SET  MULTI_USER 
GO

ALTER DATABASE [MYB] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO

ALTER DATABASE [MYB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MYB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MYB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MYB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MYB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MYB] SET  READ_WRITE 
GO

